{% set name = "jinja2-highlight" %}
{% set version = "0.6.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: fad47890c12f1a270a45cd0783cad84cb8f9770071395df87be473ec6d611b09

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jinja2 >=2.4
    - pygments >=1.5
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - jinja2_highlight

about:
  home: "https://github.com/tlatsas/jinja2-highlight"
  license: "GPL-3.0-only"
  license_family: GPL3
  license_file: LICENSE  
  summary: "Jinja2 extension to highlight source code using Pygments"
  doc_url:  "https://github.com/tlatsas/jinja2-highlight"
  dev_url: "https://github.com/tlatsas/jinja2-highlight"

extra:
  recipe-maintainers:
    - fhoehle
